Use preshared keys and make pingable
freifunkMUC/wg-embed pull request #15
Opened 2023-01-20 17:16 UTC by fbuetler

See TODO for more information.

### Added features

* peer accepts a pre-shared key (see [5.2 Optional Pre-shared Symmetric Key](https://www.wireguard.com/papers/wireguard.pdf))
* make wireguard pingable

2023-02-12 16:20 UTC, T0biii requested changes

2023-02-12 16:20 UTC, T0biii commented on .github/dependabot.yml
> +    assignees: [inventage/wg-access-server]
i think this should not be changed?

2023-02-12 16:20 UTC, T0biii commented on go.mod
> +module github.com/inventage/wg-embed
i think this should not be changed?

2023-02-13 16:48 UTC, fbuetler commented on .github/dependabot.yml
> +    assignees: [inventage/wg-access-server]
thanks, I reverted the changes

2023-02-13 16:49 UTC, fbuetler commented on go.mod
> +module github.com/inventage/wg-embed
dito

2023-03-12 15:46 UTC, GoliathLabs approved these changes

2023-03-12 16:00 UTC, merged